---
# tasks file for mysql_db
- name: Install MySQL DB
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client

- name: Start MySQL Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Application Database
  mysql_db: name={{ db_name }} state=ALL

- name: Create Database User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
    state: present
    host: "%"
